package com.sig.view;

import com.sig.controller.ButtonsActionListener;
import com.sig.controller.LineSelectorListener;
import com.sig.controller.MenuItemActionListeners;
import com.sig.model.InvHeaderTableModel;
import com.sig.model.InvoiceHeader;
import com.sig.model.InvoiceLine;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

public class InvoiceForm extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceForm
     */
    public InvoiceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invTable = new javax.swing.JTable();
        invoicesTable = new javax.swing.JLabel();
        numLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        custLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        createInvoiceBtn = new javax.swing.JButton();
        deleteInvoiceBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        linesTable = new javax.swing.JTable();
        createLineBtn = new javax.swing.JButton();
        deleteLineBtn = new javax.swing.JButton();
        invITemsLbl = new javax.swing.JLabel();
        invNumLbl = new javax.swing.JLabel();
        invDateLbl = new javax.swing.JLabel();
        customerNameLbl = new javax.swing.JLabel();
        invTotalLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadFileButton = new javax.swing.JMenuItem();
        saveFileButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        invTable.getSelectionModel().addListSelectionListener(selectorListener);
        jScrollPane1.setViewportView(invTable);

        invoicesTable.setText("Invoices Table");

        numLbl.setText("Invoice Number");

        dateLbl.setText("Invoice Date");

        custLbl.setText("Customer Name");

        totalLbl.setText("Invoice Total");

        createInvoiceBtn.setText("Create New Invoice");
        createInvoiceBtn.addActionListener(btnsActionListener);

        deleteInvoiceBtn.setText("Delete Invoice");
        deleteInvoiceBtn.addActionListener(btnsActionListener);

        linesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(linesTable);

        createLineBtn.setText("Create Line");
        createLineBtn.addActionListener(btnsActionListener);

        deleteLineBtn.setText("Delete Line");
        deleteLineBtn.addActionListener(btnsActionListener);

        invITemsLbl.setText("Invoices Items");

        jMenu1.setText("File");

        loadFileButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loadFileButton.setMnemonic('L');
        loadFileButton.setText("Load File");
        loadFileButton.addActionListener(menuActionListener);
        loadFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileButtonActionPerformed(evt);
            }
        });
        jMenu1.add(loadFileButton);

        saveFileButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveFileButton.setMnemonic('S');
        saveFileButton.setText("Save File");
        saveFileButton.addActionListener(menuActionListener);
        jMenu1.add(saveFileButton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(createInvoiceBtn)
                .addGap(75, 75, 75)
                .addComponent(deleteInvoiceBtn)
                .addGap(166, 166, 166)
                .addComponent(createLineBtn)
                .addGap(75, 75, 75)
                .addComponent(deleteLineBtn)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoicesTable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invITemsLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numLbl)
                                    .addComponent(dateLbl)
                                    .addComponent(custLbl)
                                    .addComponent(totalLbl))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invTotalLbl)
                                    .addComponent(customerNameLbl)
                                    .addComponent(invDateLbl)
                                    .addComponent(invNumLbl))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(invoicesTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numLbl)
                            .addComponent(invNumLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLbl)
                            .addComponent(invDateLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custLbl)
                            .addComponent(customerNameLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLbl)
                            .addComponent(invTotalLbl))
                        .addGap(18, 18, 18)
                        .addComponent(invITemsLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createInvoiceBtn)
                    .addComponent(deleteInvoiceBtn)
                    .addComponent(createLineBtn)
                    .addComponent(deleteLineBtn))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createInvoiceBtn;
    private javax.swing.JButton createLineBtn;
    private javax.swing.JLabel custLbl;
    private javax.swing.JLabel customerNameLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JButton deleteInvoiceBtn;
    private javax.swing.JButton deleteLineBtn;
    private javax.swing.JLabel invDateLbl;
    private javax.swing.JLabel invITemsLbl;
    private javax.swing.JLabel invNumLbl;
    private javax.swing.JTable invTable;
    private javax.swing.JLabel invTotalLbl;
    private javax.swing.JLabel invoicesTable;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable linesTable;
    private javax.swing.JMenuItem loadFileButton;
    private javax.swing.JLabel numLbl;
    private javax.swing.JMenuItem saveFileButton;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
   
    public static SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy"); 
    private ButtonsActionListener btnsActionListener = new ButtonsActionListener(this);
    private MenuItemActionListeners menuActionListener = new MenuItemActionListeners(this);
    private InvHeaderTableModel invHeaderTM;
    private ArrayList<InvoiceHeader> invoicesArray;
    private  ArrayList<InvoiceLine> linesArray;
    private LineSelectorListener selectorListener = new LineSelectorListener(this);

    public ArrayList<InvoiceHeader> getInvoicesArray() {
        return invoicesArray;
    }

    
    
    public void setInvoicesArray(ArrayList<InvoiceHeader> invoicesArray) {
        this.invoicesArray = invoicesArray;
    }
    
    
    public InvoiceHeader getInvObject(int invId){
       for(InvoiceHeader inv : invoicesArray){
           if(inv.getNumber()==invId){
               return inv;
           }
       }
        return null;
    }

    public ArrayList<InvoiceLine> getLinesArray() {
        return linesArray;
    }

    public void setLinesArray(ArrayList<InvoiceLine> linesArray) {
        this.linesArray = linesArray;
    }
    
    

    public InvHeaderTableModel getInvHeaderTM() {
        return invHeaderTM;
    }

    public void setInvHeaderTM(InvHeaderTableModel invHeaderTM) {
        this.invHeaderTM = invHeaderTM;
    }
    

    public JTable getInvTable() {
        return invTable;
    }

    public JTable getLinesTable() {
        return linesTable;
    }

    public JLabel getCustomerNameLbl() {
        return customerNameLbl;
    }

    public JLabel getInvDateLbl() {
        return invDateLbl;
    }


    public JLabel getInvNumLbl() {
        return invNumLbl;
    }

    public JLabel getInvTotalLbl() {
        return invTotalLbl;
    }

    public ButtonsActionListener getBtnsActionListener() {
        return btnsActionListener;
    }




    
    
    
}
